stages:
  - build
  - test
  - package

variables:
  plugin: ActionsExtension
  engine_version: 25

cache:
  paths:
    - Build/

before_script:
  # Download Piperift's CICD scripts
  - git clone https://github.com/PipeRift/CICDScripts Lib

build:
  stage: build
  script:
    - cmd.exe /c Lib/BuildPlugin.bat

test:
  stage: test
  script:
    - py Lib/test_plugin.py

upload:
  stage: package
  script:
    - cmd.exe /c Lib/CompressPlugin.bat
    - py Lib/upload.py
